"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-08-12 08:45:41.358158
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# `UtcDateTime` es un tipo propio (`TypeDecorator`) que normaliza toda marca de
# tiempo a UTC. Alembic lo referencia por su ruta completa al generar la
# migración, así que el módulo tiene que estar importado aquí.
import app.infrastructure.models.mixins
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_codigo'), 'categorias', ['codigo'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('canal', sa.String(length=40), nullable=True),
    sa.Column('vendedor', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_canal'), 'clientes', ['canal'], unique=False)
    op.create_index(op.f('ix_clientes_nit'), 'clientes', ['nit'], unique=True)
    op.create_index(op.f('ix_clientes_vendedor'), 'clientes', ['vendedor'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_codigo'), 'grupos', ['codigo'], unique=True)
    op.create_table('intentos_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('motivo', sa.String(length=120), nullable=True),
    sa.Column('fecha', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intentos_usuario_fecha', 'intentos_acceso', ['usuario', 'fecha'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=True),
    sa.Column('ultimo_acceso', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=True),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_usuario'), 'usuarios', ['usuario'], unique=True)
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('corridas_ingesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuando', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fuente', sa.String(length=20), nullable=False),
    sa.Column('desde', sa.Date(), nullable=True),
    sa.Column('hasta', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('filas_leidas', sa.Integer(), nullable=False),
    sa.Column('aceptadas', sa.Integer(), nullable=False),
    sa.Column('rechazadas', sa.Integer(), nullable=False),
    sa.Column('duracion_ms', sa.Integer(), nullable=True),
    sa.Column('origen', sa.String(length=300), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corridas_cuando', 'corridas_ingesta', ['cuando'], unique=False)
    op.create_table('mapeo_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto_siesa', sa.String(length=120), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapeo_categorias_categoria_id'), 'mapeo_categorias', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_mapeo_categorias_texto_siesa'), 'mapeo_categorias', ['texto_siesa'], unique=True)
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('cerrado', sa.Boolean(), nullable=False),
    sa.Column('cerrado_por_id', sa.Integer(), nullable=True),
    sa.Column('cerrado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=True),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='ck_periodo_mes_valido'),
    sa.ForeignKeyConstraint(['cerrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes', name='uq_periodo_anio_mes')
    )
    op.create_index('ix_periodo_orden', 'periodos', ['anio', 'mes'], unique=False)
    op.create_table('puntos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_co', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('descripcion_siesa', sa.String(length=120), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('presupuestado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puntos_venta_codigo_co'), 'puntos_venta', ['codigo_co'], unique=True)
    op.create_index(op.f('ix_puntos_venta_grupo_id'), 'puntos_venta', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_puntos_venta_zona_id'), 'puntos_venta', ['zona_id'], unique=False)
    op.create_table('calendario_zona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=False),
    sa.Column('dias_habiles', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dias_trabajados', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fecha_corte', sa.Date(), nullable=True),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dias_habiles > 0', name='ck_calendario_habiles_positivos'),
    sa.CheckConstraint('dias_trabajados IS NULL OR dias_trabajados >= 0', name='ck_calendario_trabajados_no_negativos'),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'zona_id', name='uq_calendario_periodo_zona')
    )
    op.create_index(op.f('ix_calendario_zona_periodo_id'), 'calendario_zona', ['periodo_id'], unique=False)
    op.create_index(op.f('ix_calendario_zona_zona_id'), 'calendario_zona', ['zona_id'], unique=False)
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('kilos', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('actualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('kilos >= 0', name='ck_presupuesto_kilos_no_negativo'),
    sa.CheckConstraint('monto >= 0', name='ck_presupuesto_monto_no_negativo'),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'punto_venta_id', 'categoria_id', name='uq_presupuesto_pdv_categoria')
    )
    op.create_index('ix_presupuesto_periodo_pdv', 'presupuestos', ['periodo_id', 'punto_venta_id'], unique=False)
    op.create_index(op.f('ix_presupuestos_categoria_id'), 'presupuestos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_presupuestos_periodo_id'), 'presupuestos', ['periodo_id'], unique=False)
    op.create_index(op.f('ix_presupuestos_punto_venta_id'), 'presupuestos', ['punto_venta_id'], unique=False)
    op.create_table('rechazos_ingesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corrida_id', sa.Integer(), nullable=False),
    sa.Column('fila', sa.Integer(), nullable=True),
    sa.Column('campo', sa.String(length=60), nullable=True),
    sa.Column('valor', sa.String(length=300), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['corrida_id'], ['corridas_ingesta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rechazos_corrida', 'rechazos_ingesta', ['corrida_id'], unique=False)
    op.create_table('usuario_puntos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'punto_venta_id', name='uq_usuario_punto_venta')
    )
    op.create_index(op.f('ix_usuario_puntos_venta_punto_venta_id'), 'usuario_puntos_venta', ['punto_venta_id'], unique=False)
    op.create_index(op.f('ix_usuario_puntos_venta_usuario_id'), 'usuario_puntos_venta', ['usuario_id'], unique=False)
    op.create_table('venta_lineas',
    # `BigInteger` en PostgreSQL y SQL Server; `Integer` en SQLite, que solo
    # autoincrementa sobre su `INTEGER PRIMARY KEY`. Ver el modelo `VentaLinea`.
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('corrida_id', sa.Integer(), nullable=True),
    sa.Column('valor_subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('costo_promedio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cantidad_inv', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('margen_siesa', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('categoria_siesa', sa.String(length=120), nullable=True),
    sa.Column('nit_cliente', sa.String(length=30), nullable=True),
    sa.Column('domicilio', sa.Boolean(), nullable=True),
    sa.Column('clase_cliente', sa.String(length=60), nullable=True),
    sa.Column('condicion_pago', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['corrida_id'], ['corridas_ingesta.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_venta_corrida', 'venta_lineas', ['corrida_id'], unique=False)
    op.create_index('ix_venta_fecha_pdv', 'venta_lineas', ['fecha', 'punto_venta_id'], unique=False)
    op.create_index(op.f('ix_venta_lineas_condicion_pago'), 'venta_lineas', ['condicion_pago'], unique=False)
    op.create_index('ix_venta_periodo_cliente', 'venta_lineas', ['periodo_id', 'cliente_id'], unique=False)
    op.create_index('ix_venta_periodo_pdv_categoria', 'venta_lineas', ['periodo_id', 'fecha', 'punto_venta_id', 'categoria_id'], unique=False)
    op.create_table('presupuesto_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=True),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=20), nullable=False),
    sa.Column('valor_anterior', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('valor_nuevo', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('motivo', sa.String(length=400), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('cuando', app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historial_periodo_pdv', 'presupuesto_historial', ['periodo_id', 'punto_venta_id', 'cuando'], unique=False)
    op.create_index(op.f('ix_presupuesto_historial_presupuesto_id'), 'presupuesto_historial', ['presupuesto_id'], unique=False)
    op.create_index(op.f('ix_presupuesto_historial_usuario_id'), 'presupuesto_historial', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presupuesto_historial_usuario_id'), table_name='presupuesto_historial')
    op.drop_index(op.f('ix_presupuesto_historial_presupuesto_id'), table_name='presupuesto_historial')
    op.drop_index('ix_historial_periodo_pdv', table_name='presupuesto_historial')
    op.drop_table('presupuesto_historial')
    op.drop_index('ix_venta_periodo_pdv_categoria', table_name='venta_lineas')
    op.drop_index('ix_venta_periodo_cliente', table_name='venta_lineas')
    op.drop_index(op.f('ix_venta_lineas_condicion_pago'), table_name='venta_lineas')
    op.drop_index('ix_venta_fecha_pdv', table_name='venta_lineas')
    op.drop_index('ix_venta_corrida', table_name='venta_lineas')
    op.drop_table('venta_lineas')
    op.drop_index(op.f('ix_usuario_puntos_venta_usuario_id'), table_name='usuario_puntos_venta')
    op.drop_index(op.f('ix_usuario_puntos_venta_punto_venta_id'), table_name='usuario_puntos_venta')
    op.drop_table('usuario_puntos_venta')
    op.drop_index('ix_rechazos_corrida', table_name='rechazos_ingesta')
    op.drop_table('rechazos_ingesta')
    op.drop_index(op.f('ix_presupuestos_punto_venta_id'), table_name='presupuestos')
    op.drop_index(op.f('ix_presupuestos_periodo_id'), table_name='presupuestos')
    op.drop_index(op.f('ix_presupuestos_categoria_id'), table_name='presupuestos')
    op.drop_index('ix_presupuesto_periodo_pdv', table_name='presupuestos')
    op.drop_table('presupuestos')
    op.drop_index(op.f('ix_calendario_zona_zona_id'), table_name='calendario_zona')
    op.drop_index(op.f('ix_calendario_zona_periodo_id'), table_name='calendario_zona')
    op.drop_table('calendario_zona')
    op.drop_index(op.f('ix_puntos_venta_zona_id'), table_name='puntos_venta')
    op.drop_index(op.f('ix_puntos_venta_grupo_id'), table_name='puntos_venta')
    op.drop_index(op.f('ix_puntos_venta_codigo_co'), table_name='puntos_venta')
    op.drop_table('puntos_venta')
    op.drop_index('ix_periodo_orden', table_name='periodos')
    op.drop_table('periodos')
    op.drop_index(op.f('ix_mapeo_categorias_texto_siesa'), table_name='mapeo_categorias')
    op.drop_index(op.f('ix_mapeo_categorias_categoria_id'), table_name='mapeo_categorias')
    op.drop_table('mapeo_categorias')
    op.drop_index('ix_corridas_cuando', table_name='corridas_ingesta')
    op.drop_table('corridas_ingesta')
    op.drop_table('zonas')
    op.drop_index(op.f('ix_usuarios_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('ix_intentos_usuario_fecha', table_name='intentos_acceso')
    op.drop_table('intentos_acceso')
    op.drop_index(op.f('ix_grupos_codigo'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_clientes_vendedor'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nit'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_canal'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categorias_codigo'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
