"""unidad agropecuaria: venta, dimensiones y presupuesto por dimension

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-20 20:48:42.991368
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# `UtcDateTime` es un tipo propio (`TypeDecorator`). Alembic lo referencia por su
# ruta completa al autogenerar, asi que el modulo tiene que estar importado aqui.
import app.infrastructure.models.mixins
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agro_dimensiones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("clave", sa.String(length=60), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "creado_en", app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "actualizado_en",
            app.infrastructure.models.mixins.UtcDateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo", "clave", name="uq_agro_dimension_tipo_clave"),
    )
    op.create_index(
        "ix_agro_dimension_tipo_nombre", "agro_dimensiones", ["tipo", "nombre"], unique=False
    )
    op.create_table(
        "agro_corridas_ingesta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "cuando", app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("fuente", sa.String(length=20), nullable=False),
        sa.Column("desde", sa.Date(), nullable=True),
        sa.Column("hasta", sa.Date(), nullable=True),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("filas_leidas", sa.Integer(), nullable=False),
        sa.Column("aceptadas", sa.Integer(), nullable=False),
        sa.Column("rechazadas", sa.Integer(), nullable=False),
        sa.Column("impuesto", sa.Integer(), nullable=False),
        sa.Column("duracion_ms", sa.Integer(), nullable=True),
        sa.Column("origen", sa.String(length=300), nullable=True),
        sa.Column("mensaje", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agro_corridas_cuando", "agro_corridas_ingesta", ["cuando"], unique=False)
    op.create_table(
        "agro_calendario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("periodo_id", sa.Integer(), nullable=False),
        sa.Column("centro_id", sa.Integer(), nullable=False),
        sa.Column("dias_habiles", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("dias_trabajados", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("fecha_corte", sa.Date(), nullable=True),
        sa.Column("actualizado_por_id", sa.Integer(), nullable=True),
        sa.Column(
            "creado_en", app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "actualizado_en",
            app.infrastructure.models.mixins.UtcDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint("dias_habiles > 0", name="ck_agro_calendario_habiles_positivos"),
        sa.CheckConstraint(
            "dias_trabajados IS NULL OR dias_trabajados >= 0",
            name="ck_agro_calendario_trabajados_no_negativos",
        ),
        sa.ForeignKeyConstraint(
            ["actualizado_por_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["centro_id"],
            ["agro_dimensiones.id"],
        ),
        sa.ForeignKeyConstraint(["periodo_id"], ["periodos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("periodo_id", "centro_id", name="uq_agro_calendario_periodo_centro"),
    )
    op.create_index(
        op.f("ix_agro_calendario_centro_id"), "agro_calendario", ["centro_id"], unique=False
    )
    op.create_index(
        op.f("ix_agro_calendario_periodo_id"), "agro_calendario", ["periodo_id"], unique=False
    )
    op.create_table(
        "agro_presupuestos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("periodo_id", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(length=30), nullable=False),
        sa.Column("clave", sa.String(length=60), nullable=False),
        sa.Column("etiqueta", sa.String(length=200), nullable=True),
        sa.Column("monto", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("kilos", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("actualizado_por_id", sa.Integer(), nullable=True),
        sa.Column(
            "creado_en", app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "actualizado_en",
            app.infrastructure.models.mixins.UtcDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dimension = 'vendedor' OR dimension = 'centro_operacion' OR dimension = 'especie' OR dimension = 'tipo_comercial'",
            name="ck_agro_presupuesto_dimension",
        ),
        sa.CheckConstraint("kilos >= 0", name="ck_agro_presupuesto_kilos_no_negativo"),
        sa.CheckConstraint("monto >= 0", name="ck_agro_presupuesto_monto_no_negativo"),
        sa.ForeignKeyConstraint(
            ["actualizado_por_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["periodo_id"],
            ["periodos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "periodo_id", "dimension", "clave", name="uq_agro_presupuesto_dimension_clave"
        ),
    )
    op.create_index(
        "ix_agro_presupuesto_periodo_dimension",
        "agro_presupuestos",
        ["periodo_id", "dimension", "clave"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agro_presupuestos_periodo_id"), "agro_presupuestos", ["periodo_id"], unique=False
    )
    op.create_table(
        "agro_rechazos_ingesta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("corrida_id", sa.Integer(), nullable=False),
        sa.Column("fila", sa.Integer(), nullable=True),
        sa.Column("campo", sa.String(length=60), nullable=True),
        sa.Column("valor", sa.String(length=300), nullable=True),
        sa.Column("motivo", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(["corrida_id"], ["agro_corridas_ingesta.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agro_rechazos_corrida", "agro_rechazos_ingesta", ["corrida_id"], unique=False
    )
    op.create_table(
        "agro_venta_lineas",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("periodo_id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("centro_id", sa.Integer(), nullable=False),
        sa.Column("tipo_item_id", sa.Integer(), nullable=False),
        sa.Column("especie_id", sa.Integer(), nullable=False),
        sa.Column("tipo_comercial_id", sa.Integer(), nullable=False),
        sa.Column("grupo_id", sa.Integer(), nullable=False),
        sa.Column("vendedor_id", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("es_impuesto", sa.Boolean(), nullable=False),
        sa.Column("cantidad_inv", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("kilos_total", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("valor_bruto", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("descuentos", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("valor_subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_neto", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_costo", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("utilidad_bruta", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("margen_siesa", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("lineas_facturadas", sa.Integer(), nullable=False),
        sa.Column("tipo_item_siesa", sa.String(length=60), nullable=True),
        sa.Column("corrida_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["centro_id"],
            ["agro_dimensiones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["agro_dimensiones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["corrida_id"],
            ["agro_corridas_ingesta.id"],
        ),
        sa.ForeignKeyConstraint(
            ["especie_id"],
            ["agro_dimensiones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grupo_id"],
            ["agro_dimensiones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["agro_dimensiones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["periodo_id"],
            ["periodos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_comercial_id"],
            ["agro_dimensiones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tipo_item_id"],
            ["agro_dimensiones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendedor_id"],
            ["agro_dimensiones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agro_venta_corrida", "agro_venta_lineas", ["corrida_id"], unique=False)
    op.create_index(
        "ix_agro_venta_fecha_centro", "agro_venta_lineas", ["fecha", "centro_id"], unique=False
    )
    op.create_index(
        "ix_agro_venta_periodo_fecha",
        "agro_venta_lineas",
        ["periodo_id", "fecha", "es_impuesto"],
        unique=False,
    )
    op.create_index(
        "ix_agro_venta_vendedor_cliente",
        "agro_venta_lineas",
        ["periodo_id", "vendedor_id", "cliente_id"],
        unique=False,
    )
    op.create_table(
        "agro_presupuesto_historial",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("presupuesto_id", sa.Integer(), nullable=True),
        sa.Column("periodo_id", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(length=30), nullable=False),
        sa.Column("clave", sa.String(length=60), nullable=False),
        sa.Column("campo", sa.String(length=20), nullable=False),
        sa.Column("valor_anterior", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("valor_nuevo", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("motivo", sa.String(length=400), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column(
            "cuando", app.infrastructure.models.mixins.UtcDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["periodo_id"],
            ["periodos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["presupuesto_id"],
            ["agro_presupuestos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agro_historial_periodo_dimension",
        "agro_presupuesto_historial",
        ["periodo_id", "dimension", "cuando"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agro_presupuesto_historial_presupuesto_id"),
        "agro_presupuesto_historial",
        ["presupuesto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agro_presupuesto_historial_usuario_id"),
        "agro_presupuesto_historial",
        ["usuario_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_agro_presupuesto_historial_usuario_id"), table_name="agro_presupuesto_historial"
    )
    op.drop_index(
        op.f("ix_agro_presupuesto_historial_presupuesto_id"),
        table_name="agro_presupuesto_historial",
    )
    op.drop_index("ix_agro_historial_periodo_dimension", table_name="agro_presupuesto_historial")
    op.drop_table("agro_presupuesto_historial")
    op.drop_index("ix_agro_venta_vendedor_cliente", table_name="agro_venta_lineas")
    op.drop_index("ix_agro_venta_periodo_fecha", table_name="agro_venta_lineas")
    op.drop_index("ix_agro_venta_fecha_centro", table_name="agro_venta_lineas")
    op.drop_index("ix_agro_venta_corrida", table_name="agro_venta_lineas")
    op.drop_table("agro_venta_lineas")
    op.drop_index("ix_agro_rechazos_corrida", table_name="agro_rechazos_ingesta")
    op.drop_table("agro_rechazos_ingesta")
    op.drop_index(op.f("ix_agro_presupuestos_periodo_id"), table_name="agro_presupuestos")
    op.drop_index("ix_agro_presupuesto_periodo_dimension", table_name="agro_presupuestos")
    op.drop_table("agro_presupuestos")
    op.drop_index(op.f("ix_agro_calendario_periodo_id"), table_name="agro_calendario")
    op.drop_index(op.f("ix_agro_calendario_centro_id"), table_name="agro_calendario")
    op.drop_table("agro_calendario")
    op.drop_index("ix_agro_corridas_cuando", table_name="agro_corridas_ingesta")
    op.drop_table("agro_corridas_ingesta")
    op.drop_index("ix_agro_dimension_tipo_nombre", table_name="agro_dimensiones")
    op.drop_table("agro_dimensiones")
    # ### end Alembic commands ###
